/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as AnalysisIndexRouteImport } from './routes/analysis.index'
import { Route as AnalysisV1RouteImport } from './routes/analysis.v1'
import { Route as AnalysisV2RouteImport } from './routes/analysis.v2'
import { Route as ApiAnalysisRouteImport } from './routes/api/analysis'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisIndexRoute = AnalysisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnalysisRoute,
} as any)
const AnalysisV1Route = AnalysisV1RouteImport.update({
  id: '/v1',
  path: '/v1',
  getParentRoute: () => AnalysisRoute,
} as any)
const AnalysisV2Route = AnalysisV2RouteImport.update({
  id: '/v2',
  path: '/v2',
  getParentRoute: () => AnalysisRoute,
} as any)
const ApiAnalysisRoute = ApiAnalysisRouteImport.update({
  id: '/api/analysis',
  path: '/api/analysis',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRouteWithChildren
  '/backtest': typeof BacktestRoute
  '/analysis/v1': typeof AnalysisV1Route
  '/analysis/v2': typeof AnalysisV2Route
  '/api/analysis': typeof ApiAnalysisRoute
  '/analysis/': typeof AnalysisIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backtest': typeof BacktestRoute
  '/analysis/v1': typeof AnalysisV1Route
  '/analysis/v2': typeof AnalysisV2Route
  '/api/analysis': typeof ApiAnalysisRoute
  '/analysis': typeof AnalysisIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRouteWithChildren
  '/backtest': typeof BacktestRoute
  '/analysis/v1': typeof AnalysisV1Route
  '/analysis/v2': typeof AnalysisV2Route
  '/api/analysis': typeof ApiAnalysisRoute
  '/analysis/': typeof AnalysisIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/backtest'
    | '/analysis/v1'
    | '/analysis/v2'
    | '/api/analysis'
    | '/analysis/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backtest'
    | '/analysis/v1'
    | '/analysis/v2'
    | '/api/analysis'
    | '/analysis'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/backtest'
    | '/analysis/v1'
    | '/analysis/v2'
    | '/api/analysis'
    | '/analysis/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRouteWithChildren
  BacktestRoute: typeof BacktestRoute
  ApiAnalysisRoute: typeof ApiAnalysisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/': {
      id: '/analysis/'
      path: '/'
      fullPath: '/analysis/'
      preLoaderRoute: typeof AnalysisIndexRouteImport
      parentRoute: typeof AnalysisRoute
    }
    '/analysis/v1': {
      id: '/analysis/v1'
      path: '/v1'
      fullPath: '/analysis/v1'
      preLoaderRoute: typeof AnalysisV1RouteImport
      parentRoute: typeof AnalysisRoute
    }
    '/analysis/v2': {
      id: '/analysis/v2'
      path: '/v2'
      fullPath: '/analysis/v2'
      preLoaderRoute: typeof AnalysisV2RouteImport
      parentRoute: typeof AnalysisRoute
    }
    '/api/analysis': {
      id: '/api/analysis'
      path: '/api/analysis'
      fullPath: '/api/analysis'
      preLoaderRoute: typeof ApiAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AnalysisRouteChildren {
  AnalysisV1Route: typeof AnalysisV1Route
  AnalysisV2Route: typeof AnalysisV2Route
  AnalysisIndexRoute: typeof AnalysisIndexRoute
}

const AnalysisRouteChildren: AnalysisRouteChildren = {
  AnalysisV1Route: AnalysisV1Route,
  AnalysisV2Route: AnalysisV2Route,
  AnalysisIndexRoute: AnalysisIndexRoute,
}

const AnalysisRouteWithChildren = AnalysisRoute._addFileChildren(
  AnalysisRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRouteWithChildren,
  BacktestRoute: BacktestRoute,
  ApiAnalysisRoute: ApiAnalysisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
